/* Prepares everything the Worker cannot read at runtime.

   The Workers runtime has no filesystem, so the two things the local Node
   server read from disk have to be baked in before deploy:

     lessons/*.md            -> src/lessons.generated.js  (bundled into the Worker)
     tracker-backend/public  -> dist/public               (uploaded as static assets)

   Both outputs are generated and git-ignored. Run: npm run build
*/

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const WORKER_DIR = path.join(HERE, '..');
const REPO = path.join(WORKER_DIR, '..');

const LESSONS_DIR = path.join(REPO, 'lessons');
const PUBLIC_SRC = path.join(REPO, 'tracker-backend', 'public');
const DIST_PUBLIC = path.join(WORKER_DIR, 'dist', 'public');
const LESSONS_OUT = path.join(WORKER_DIR, 'src', 'lessons.generated.js');

/* ------------------------------ 1. lessons ------------------------------- */

if (!fs.existsSync(LESSONS_DIR)) {
  console.error(`build failed: no lessons folder at ${LESSONS_DIR}`);
  process.exit(1);
}

const lessons = {};
for (const file of fs.readdirSync(LESSONS_DIR).sort()) {
  const match = /^Day-(\d{2})-.*\.md$/.exec(file);
  if (match) lessons[Number(match[1])] = fs.readFileSync(path.join(LESSONS_DIR, file), 'utf8');
}

const found = Object.keys(lessons).length;
if (found === 0) {
  console.error(`build failed: no Day-NN-*.md files in ${LESSONS_DIR}`);
  process.exit(1);
}

const missing = [];
for (let day = 1; day <= 30; day++) if (!lessons[day]) missing.push(day);
if (missing.length) console.warn(`  warning: no lesson file for day(s) ${missing.join(', ')}`);

// JSON.stringify handles every quote, backtick and backslash in the markdown.
const body = Object.keys(lessons)
  .map(Number)
  .sort((a, b) => a - b)
  .map((day) => `  ${day}: ${JSON.stringify(lessons[day])},`)
  .join('\n');

fs.writeFileSync(
  LESSONS_OUT,
  `// GENERATED by scripts/build.mjs from lessons/*.md - do not edit.\nexport const LESSONS = {\n${body}\n};\n`
);

/* --------------------------- 2. static assets ---------------------------- */

if (!fs.existsSync(PUBLIC_SRC)) {
  console.error(`build failed: no frontend at ${PUBLIC_SRC}`);
  process.exit(1);
}

// Empty the folder rather than deleting it: on Windows a running `wrangler dev`
// holds a handle on dist/, and removing the directory itself then fails EPERM.
// Anything that cannot be removed is simply overwritten by the copy below.
if (fs.existsSync(DIST_PUBLIC)) {
  for (const entry of fs.readdirSync(DIST_PUBLIC)) {
    try {
      fs.rmSync(path.join(DIST_PUBLIC, entry), { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
    } catch (err) {
      console.warn(`  warning: could not remove dist/public/${entry} (${err.code}) - overwriting instead`);
    }
  }
}
fs.mkdirSync(DIST_PUBLIC, { recursive: true });
fs.cpSync(PUBLIC_SRC, DIST_PUBLIC, { recursive: true });

// The local server set these headers in code. Static assets never reach the
// Worker, so on Cloudflare they come from _headers instead. Cloudflare reads
// this file as configuration and does not serve it.
fs.writeFileSync(
  path.join(DIST_PUBLIC, '_headers'),
  `/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'
`
);

const assetCount = fs.readdirSync(DIST_PUBLIC, { recursive: true }).length;
console.log(`  lessons bundled: ${found}`);
console.log(`  assets staged:   ${assetCount} entries -> dist/public`);
