/* Turns the local data/db.json into SQL you can load into D1.

     node scripts/migrate-db.mjs
     npx wrangler d1 execute git-challenge-tracker --remote --file=./migrate.sql

   Progress carries over exactly. Passwords do NOT: the old hashes are scrypt,
   which the Workers runtime cannot compute, so every migrated account lands
   with an unusable password. Give each one a new password afterwards:

     node scripts/set-password.mjs you@example.com "your new password"
*/

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const WORKER_DIR = path.join(HERE, '..');
const DB_FILE = process.argv[2] || path.join(WORKER_DIR, '..', 'data', 'db.json');
const OUT = path.join(WORKER_DIR, 'migrate.sql');

if (!fs.existsSync(DB_FILE)) {
  console.error(`no db.json at ${DB_FILE}`);
  console.error('pass a path explicitly:  node scripts/migrate-db.mjs ../data/db.json');
  process.exit(1);
}

const db = JSON.parse(fs.readFileSync(DB_FILE, 'utf8'));
const quote = (value) => `'${String(value).replace(/'/g, "''")}'`;

const lines = [
  '-- GENERATED by scripts/migrate-db.mjs - one-time import of data/db.json.',
  '-- Passwords are deliberately unusable; reset each one with scripts/set-password.mjs.',
  '',
];

let userCount = 0;
let dayCount = 0;

for (const user of db.users || []) {
  userCount++;
  lines.push(
    'INSERT OR IGNORE INTO users (id, email, name, password, created_at, start_date) VALUES (' +
      [
        quote(user.id),
        quote(String(user.email).trim().toLowerCase()),
        quote(user.name),
        // Not a valid pbkdf2-sha256 record, so verifyPassword always returns
        // false - the account exists but cannot be signed into until reset.
        quote('reset-required'),
        quote(user.createdAt || new Date().toISOString()),
        quote(user.startDate || new Date().toISOString().slice(0, 10)),
      ].join(', ') +
      ');'
  );
}

lines.push('');

for (const [userId, days] of Object.entries(db.activities || {})) {
  for (const [day, value] of Object.entries(days || {})) {
    const dayNum = Number(day);
    if (!Number.isInteger(dayNum) || dayNum < 1 || dayNum > 30) continue;
    dayCount++;
    lines.push(
      'INSERT OR REPLACE INTO activities (user_id, day, data, updated_at) VALUES (' +
        [
          quote(userId),
          String(dayNum),
          quote(JSON.stringify(value)),
          quote(value.updatedAt || new Date().toISOString()),
        ].join(', ') +
        ');'
    );
  }
}

fs.writeFileSync(OUT, lines.join('\n') + '\n');

console.log(`  ${userCount} user(s), ${dayCount} day record(s) -> ${OUT}`);
console.log('');
console.log('  next:');
console.log('    npx wrangler d1 execute git-challenge-tracker --remote --file=./migrate.sql');
for (const user of db.users || []) {
  console.log(`    node scripts/set-password.mjs ${String(user.email).trim().toLowerCase()} "new password"`);
}
